name: NeteaseMusic
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * *"
  pull_request:
    branches: 
      - main

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: npm install
      - name: index.js
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REFS: ${{ github.ref }}
          USER_ID: 1755813132
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          REPO: "netease-music-card-fixed"
          AUTHOR: "luyanci"
